name: xgboost-mnist-from-for-s3
spec:	
    instancecount: 1
    instancetype: ml.m4.xlarge
    volumesize: 5
    maxruntimeinseconds: 86400
    rolearn: arn:aws:iam::123456789012:role/service-role/AmazonSageMaker-ExecutionRole
    region: us-east-2
    image: 825641698319.dkr.ecr.us-east-2.amazonaws.com/xgboost:1
    traininginputmode: File
    hyperparameters:
       max_depth: 5
       eta: 0.2
       num_round: 10
       gamma: 4
       min_child_weight: 6
       silent: 0
       objective: multi:softmax
       num_class: 10
       num_round: 10
    inputdataconfig:
      - channel: train 
        s3: 
           s3uri: https://s3-us-east-2.amazonaws.com/my-bucket/train/
      - channel: validation
        s3: 
           s3uri: https://s3-us-east-2.amazonaws.com/my-bucket/validation/
    outputpath: s3://my-buckes/xgboost/

