apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: sagemaker-k8s-operator-system
namePrefix: sagemaker-k8s-operator-
  
bases:
- ../../crd
- ../../base
- namespaced/resources

patchesStrategicMerge:
- namespaced/resources/manager_add_service_account_patch.yaml