apiVersion: v1
name: amazon-sagemaker-trainingjob
version: 0.1.0
description: A Helm chart for deploying a SageMaker TrainingJob from Kubernetes.
maintainers:
  - name: Cade Daniel
    email: cdnamz@amazon.com
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Nicholas Thomson
    email: nithomso@amazon.com
  - name: Meghna Baijal
    email: mbaijal@amazon.com
# dependencies:
#   - name: amazon-sagemaker-operator-for-k8s
#     version: ">= 1.0.0"
#     repository: https://aws.github.io/eks-charts/