apiVersion: v1
name: sagemaker-k8s-trainingjob
version: 0.1.0
description: A Helm chart for deploying the SageMaker TrainingJob for Kubernetes.
maintainers:
  - name: Cade Daniel
    email: cdnamz@amazon.com
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Nicholas Thomson
    email: nithomso@amazon.com
  - name: Meghna Baijal
    email: mbaijal@amazon.com