apiVersion: sagemaker.aws.amazon.com/v1
kind: BatchTransformJob
metadata:
  name: {{ .Values.name }}
spec:
  region: {{ .Values.spec.region }}
  modelName: {{ .Values.spec.modelname | quote }}
  transformInput: 
    dataSource: 
      s3DataSource:
        s3DataType: {{ .Values.spec.inputDataConfig.s3DataType | default "S3Prefix" }}
        s3Uri: {{ .Values.spec.inputDataConfig.s3Uri  }}
    contentType: {{ .contentType | default "text/csv" }}
  transformOutput:
    s3OutputPath: {{ .Values.spec.outputPath }}
  transformResources:
    instanceCount: {{ .Values.spec.instanceCount }}
    instanceType: {{ .Values.spec.instanceType }}
  tags:
    - key: test-key
      value: test-value
