apiVersion: v1
name: amazon-sagemaker-operator-for-k8s
version: 1.0.0
appVersion: 1.1.0
description: A Helm chart for deploying the Amazon SageMaker Operator for Kubernetes using EKS IAM roles for service accounts.
maintainers:
  - name: Gautam Kumar
    email: gauta@amazon.com
  - name: Cade Daniel
    email: cdnamz@amazon.com
  - name: Nicholas Thomson
    email: nithomso@amazon.com
  - name: Meghna Baijal
    email: mbaijal@amazon.com
keywords:
  - amazon
  - aws
  - sagemaker
  - eks