apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: sagemaker-k8s-operator-system
namePrefix: sagemaker-k8s-operator-

resources: 
 - serviceaccount.yaml

bases:
- ../base

patchesStrategicMerge:
- manager_add_service_account_patch.yaml
