
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: models.sagemaker.aws.amazon.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: Status
    type: string
  - JSONPath: .status.sageMakerModelName
    name: Sage-Maker-Model-Name
    type: string
  group: sagemaker.aws.amazon.com
  names:
    kind: Model
    listKind: ModelList
    plural: models
    singular: model
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Model is the Schema for the hostingdeployments API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ModelSpec defines the desired state of Model
          properties:
            containers:
              items:
                description: Describes the container, as part of model definition.
                properties:
                  containerHostname:
                    type: string
                  environment:
                    items:
                      description: Used in describing maps in Kubernetes.
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  image:
                    type: string
                  modelDataUrl:
                    type: string
                  modelPackageName:
                    type: string
                type: object
              type: array
            enableNetworkIsolation:
              type: boolean
            executionRoleArn:
              type: string
            primaryContainer:
              description: Describes the container, as part of model definition.
              properties:
                containerHostname:
                  type: string
                environment:
                  items:
                    description: Used in describing maps in Kubernetes.
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                image:
                  type: string
                modelDataUrl:
                  type: string
                modelPackageName:
                  type: string
              type: object
            region:
              type: string
            sageMakerEndpoint:
              type: string
            tags:
              items:
                properties:
                  key:
                    minLength: 1
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
            vpcConfig:
              properties:
                securityGroupIds:
                  items:
                    type: string
                  minItems: 1
                  type: array
                subnets:
                  items:
                    type: string
                  minItems: 1
                  type: array
              required:
              - securityGroupIds
              - subnets
              type: object
          required:
          - executionRoleArn
          - region
          type: object
        status:
          description: ModelStatus defines the observed state of Model
          properties:
            additional:
              description: Field to store additional information, for example if we are unable to check the status in sagemaker we update this.
              type: string
            lastUpdateTime:
              description: The last time this status was updated.
              format: date-time
              type: string
            modelArn:
              description: The Model ARN of the SageMaker model
              type: string
            sageMakerModelName:
              description: The name of the model in SageMaker.
              type: string
            status:
              description: The status of the model.
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
