
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: endpointconfigs.sagemaker.aws.amazon.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: Status
    type: string
  - JSONPath: .status.sageMakerEndpointConfigName
    name: Sage-Maker-EndpointConfig-Name
    type: string
  group: sagemaker.aws.amazon.com
  names:
    kind: EndpointConfig
    listKind: EndpointConfigList
    plural: endpointconfigs
    singular: endpointconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EndpointConfig is the Schema for the hostingdeployments API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EndpointConfigSpec defines the desired state of EndpointConfig
          properties:
            kmsKeyId:
              type: string
            productionVariants:
              items:
                properties:
                  acceleratorType:
                    type: string
                  initialInstanceCount:
                    format: int64
                    minimum: 1
                    type: integer
                  initialVariantWeight:
                    description: We use an int64 here instead of float because floats are not supported by the Kubernetes API. The actual traffic directed to this ProductionVariant is the ratio of this variant weight to the sum of all variant weights.
                    format: int64
                    type: integer
                  instanceType:
                    type: string
                  modelName:
                    minLength: 1
                    type: string
                  variantName:
                    minLength: 1
                    type: string
                required:
                - initialInstanceCount
                - instanceType
                - modelName
                - variantName
                type: object
              minItems: 1
              type: array
            region:
              type: string
            sageMakerEndpoint:
              type: string
            tags:
              items:
                properties:
                  key:
                    minLength: 1
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
          required:
          - productionVariants
          - region
          type: object
        status:
          description: EndpointConfigStatus defines the observed state of EndpointConfig
          properties:
            additional:
              description: Field to store additional information, for example if we are unable to check the status in sagemaker we update this.
              type: string
            endpointConfigArn:
              description: The EndpointConfig ARN of the SageMaker EndpointConfig
              type: string
            lastUpdateTime:
              description: The last time this status was updated.
              format: date-time
              type: string
            sageMakerEndpointConfigName:
              description: The name of the EndpointConfig in SageMaker.
              type: string
            status:
              description: The status of the EndpointConfig
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
