
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: batchtransformjobs.sagemaker.aws.amazon.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.transformJobStatus
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    format: date
    name: Creation-Time
    type: string
  - JSONPath: .status.sageMakerTransformJobName
    name: Sagemaker-Job-Name
    type: string
  group: sagemaker.aws.amazon.com
  names:
    kind: BatchTransformJob
    listKind: BatchTransformJobList
    plural: batchtransformjobs
    singular: batchtransformjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BatchTransformJob is the Schema for the batchtransformjobs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BatchTransformJobSpec defines the desired state of BatchTransformJob
          properties:
            batchStrategy:
              description: Batch Transform related struct
              type: string
            dataProcessing:
              properties:
                JoinSource:
                  type: string
                OutputFilter:
                  type: string
                inputFilter:
                  type: string
              type: object
            environment:
              items:
                description: Used in describing maps in Kubernetes.
                properties:
                  name:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            maxConcurrentTransforms:
              format: int64
              type: integer
            maxPayloadInMB:
              format: int64
              type: integer
            modelName:
              type: string
            region:
              minLength: 1
              type: string
            sageMakerEndpoint:
              description: A custom SageMaker endpoint to use when communicating with
                SageMaker.
              pattern: ^(https|http)://.*$
              type: string
            tags:
              items:
                properties:
                  key:
                    minLength: 1
                    type: string
                  value:
                    type: string
                required:
                - key
                - value
                type: object
              type: array
            transformInput:
              properties:
                compressionType:
                  enum:
                  - None
                  - Gzip
                  type: string
                contentType:
                  type: string
                dataSource:
                  properties:
                    s3DataSource:
                      properties:
                        s3DataType:
                          allOf:
                          - enum:
                            - S3Prefix
                            - ManifestFile
                            - AugmentedManifestFile
                          - enum:
                            - S3Prefix
                            - ManifestFile
                            - AugmentedManifestFile
                          type: string
                        s3Uri:
                          pattern: ^(https|s3)://([^/]+)/?(.*)$
                          type: string
                      required:
                      - s3DataType
                      - s3Uri
                      type: object
                  required:
                  - s3DataSource
                  type: object
                splitType:
                  type: string
              required:
              - dataSource
              type: object
            transformJobName:
              description: The SageMaker batchtransform job name. This is optional
                for the SageMaker K8s operator. If it is empty, the operator will
                populate it with a generated name.
              maxLength: 63
              type: string
            transformOutput:
              properties:
                accept:
                  type: string
                assembleWith:
                  type: string
                kmsKeyId:
                  type: string
                s3OutputPath:
                  pattern: ^(https|s3)://([^/]+)/?(.*)$
                  type: string
              required:
              - s3OutputPath
              type: object
            transformResources:
              properties:
                instanceCount:
                  format: int64
                  minimum: 1
                  type: integer
                instanceType:
                  description: Transform job has separate instance type called TransformInstanceType
                    Keeping it string
                  minLength: 1
                  type: string
                volumeKmsKeyId:
                  type: string
              required:
              - instanceCount
              - instanceType
              type: object
          required:
          - modelName
          - region
          - transformInput
          - transformOutput
          - transformResources
          type: object
        status:
          description: BatchTransformJobStatus defines the observed state of BatchTransformJob
          properties:
            additional:
              description: Field to store additional information, for example if we
                are unable to check the status we update this.
              type: string
            lastCheckTime:
              description: The last time that we checked the status of the SageMaker
                job.
              format: date-time
              type: string
            sageMakerTransformJobName:
              description: SageMaker TransformJobName job name
              type: string
            transformJobStatus:
              description: The status of the transform job. https://docs.aws.amazon.com/sagemaker/latest/dg/API_DescribeTransformJob.html
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
